site_name: ADM-CS-SPCC Documentation
site_description: Technical documentation for Advantics ADM-CS-SPCC 100kW AC/DC Active Frontend
site_url: https://documentation.advantics.fr/adm-cs-spcc
repo_url: https://github.com/ADVANTICS/documentation
repo_name: gh:ADVANTICS/documentation
edit_uri: edit/material/docs/
site_author: ADVANTICS SAS
copyright: Copyright &copy; 2017-2025 ADVANTICS SAS

# spell-checker: disable

watch:
  - "."
use_directory_urls: false

# Theme configuration
theme:
  name: material
  language: en
  logo: assets/logo.webp
  favicon: assets/favicon.svg

  palette:
    # Light theme
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark theme
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # Font
  font:
    text: Roboto
    code: Roboto Mono

  # Features
  features:
    - navigation.instant  # No reload between pages, use XHR
    - navigation.instant.progress  # Show progress-bar if longer than 400ms
    # - navigation.tracking  # Update URL with scroll
    # - navigation.tabs  # Top-level nav as tabs in header
    - navigation.tabs.sticky  # Header tabs don't dissapear when scrolling down
    - navigation.top  # Back-to-top button
    # - navigation.sections  # Group sections in the sidebar
    # - navigation.expand  # Expand all collapsible navigation sub-sections
    # - navigation.prune  # all sections collapsed by default
    - navigation.path  # Breadcrumb
    - navigation.indexes  # Intermediate section levels can have their own pages
    - navigation.footer  # Prev/Next links at the bottom
    - toc.follow  # TOC sidebar follows scroll
    # - toc.integrate  # Merge TOC into navigation sidebar
    - search.suggest  # Suggest search completion
    - search.highlight  # Highlight search results in the page
    - search.share  # Can create/copy share link for searched
    - header.autohide  # Collapse header entirely as scrolling down
    # - content.action.edit  # Top-right (middle column) edit icon
    # - content.action.view  # Top-right (middle column) view raw icon
    - content.code.copy  # Enable copy button site-wise
    - content.tabs.link

# Plugins
plugins:
  - search
  - mermaid2
  - plantuml:
      render: "server"
      puml_url: "https://www.plantuml.com/plantuml"
      output_format: "svg"
      theme_enabled: false
      retries: 5
      delay: 2
      # theme:
      #     url: _puml  # Path to custom themes, must contain advantics-theme-light.puml and advantics-theme-dark.puml
      #     light: advantics-theme-light
      #     dark: advantics-theme-dark
  - with-pdf:
      enabled_if_env: PDF_EXPORT
      output_path: pdf/adm-cs-spcc-manual.pdf
      cover_title: ADM-CS-SPCC User Manual
      cover_subtitle: Single Pistol Charge Controller (SPCC)
      author: ADVANTICS SAS
      custom_template_path: docs/assets

# Markdown extensions
markdown_extensions:
  - admonition
  # - codehilite
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex
  - toc:
      permalink: false
      baselevel: 1
  - tables
  - attr_list

# Navigation structure
nav:
  - Document Information: "index.md"
  - Technical data: "introduction.md"
  - Interfaces: "interfaces.md"
  - Examples of use: "examples.md"
  - Software Releases: "spcc_versions.md"
  - Configuration: "spcc_configuration.md"
  - Working with the SPCC:
    - Connecting to the SPCC: "advos-yocto-system/connecting.md"
    - Web UI Access: "advos-yocto-system/csm-web-ui.md"
    - SSH access: "advos-yocto-system/ssh.md"
    - Setting Static IP: "advos-yocto-system/static-ip.md"
    - Updating the Software: "advos-yocto-system/updating.md"
    - CAN Interface System Configuration: "advos-yocto-system/can-bus-configuration.md"
  - CAN bus Interfaces:
    - Introduction: "charger-can-interfaces/introduction.md"
    - Generic interface v2:
      - Sequences of action: "charger-can-interfaces/sequences_v2.md"
      - CAN databases: "charger-can-interfaces/databases_v2.md"
      - CAN messages: "charger-can-interfaces/can_v2.md"
      - Charge sequence diagram: "charger-can-interfaces/charge-sequence-diagram_v2.md"
      - Changelog: "charger-can-interfaces/changelog_v2.md"
    - Generic interface v3:
      - Sequences of action: "charger-can-interfaces/sequences_v3.md"
      - CAN databases: "charger-can-interfaces/databases_v3.md"
      - CAN messages: "charger-can-interfaces/can_v3.md"
      - Charge sequence diagram: "charger-can-interfaces/charge-sequence-diagram_v3.md"
      - Changelog: "charger-can-interfaces/changelog_v3.md"
    - V2G: "charger-can-interfaces/secc_bidirectional.md"
    - AC charging: "charger-can-interfaces/secc_ac_charging.md"
  - Features:
    - Climate control: "charger-features/secc_climate_control.md"
    - IOs on CAN: "charger-features/secc_can_ios.md"
    - Charger interfaces: "charger-features/charger_interfaces.md"
    - OCPP 1.6J: "charger-features/ocpp16j.md"
    - OCPP 2.0.1: "charger-features/ocpp201.md"
    - Plug'n'Charge:
      - Plug'n'Charge overview: "charger-features/tls_pnc/pnc_primer.md"
      - TLS & Plug'n'Charge configuration: "charger-features/tls_pnc/tls_pnc_config.md"
    - Supported Insulation Monitors: "charger-features/evse-supported-insulation-monitors.md"
    - Charger Emulator: "charger-features/charger-simulation.md"

# Extra configurations
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://advantics.fr
    - icon: fontawesome/solid/envelope
      link: mailto:contact@advantics.fr
    - icon: fontawesome/solid/phone
      link: tel:+33123456789

# Custom CSS
extra_css:
  - css/custom.css

# Extra JavaScript for Mermaid
extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js

# extra_files:
#   - _puml/advantics-theme-dark.puml
#   - _puml/advantics-theme-light.puml