name: Build landing

on:
  workflow_dispatch:
  push:
    branches:
      - material
    paths:
      - "landing/**"
      - ".github/workflows/landing.yml"

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [22]
    defaults:
      run:
        working-directory: landing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: print pwd
        run: echo $PWD

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: "landing/package.json"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: landing/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Build the landing
        run: pnpm run build

      - name: Upload to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: landing/dist/
          server-dir: public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/products/**
