name: Build docs

on:
  push:
    branches:
      - material

jobs:
  build-and-upload:
    if: github.ref == 'refs/heads/material'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        product:
          - adb-pc-ac01
          - adb-pc-dc01
          - adm-cs-spcc

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Build docs
        run: |
          source .venv/bin/activate
          cd products/${{ matrix.product }}
          PDF_EXPORT=1 mkdocs build --clean

      - name: Upload to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_DOCS_USERNAME }}
          password: ${{ secrets.FTP_DOCS_PASSWORD }}
          protocol: ftps
          local-dir: products/${{ matrix.product }}/site/
          server-dir: public_html/${{ matrix.product }}/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/pdf/*.pdf
      - name: Find and list PDF files
        run: |
          echo "Found the following PDF files:"
          find products -type f -path "*/pdf/*.pdf" -print

      # - name: Upload PDFs as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: product-pdfs
      #     path: |
      #       products/**/pdf/*.pdf
